syntax = "proto3";

package files.v1;

option go_package = "github.com/RA341/dockman/generated/files/v1";

service FileService {
  rpc List(ListRequest) returns (ListResponse) {}
  rpc Create(File) returns (Empty) {}
  rpc Copy(CopyRequest) returns (CopyResponse) {}

  rpc Delete(File) returns (Empty) {}
  rpc Exists(File) returns (Empty) {}
  rpc Rename(RenameFile) returns (Empty) {}

  rpc GetTmpls(GetTmplsRequest) returns (GetTmplsResponse) {}
  rpc WriteTmpl(WriteTmplRequest) returns (WriteTmplResponse) {}

  rpc Format(FormatRequest) returns (FormatResponse) {}
}

message WriteTmplRequest {
  string dir = 2;
  Template tmpl = 1;
}

message WriteTmplResponse {}

message GetTmplsRequest {
  string alias = 1;
}

message Template {
  string Name = 1;
  map<string, string> vars = 2;
}

message GetTmplsResponse {
  repeated Template templs = 1;
}


message CopyRequest {
  File source = 1;
  File dest = 2;
}

message CopyResponse {}

message ListRequest {
  string path = 1;
}

message ListResponse {
  repeated FsEntry entries = 1;
}

message FormatRequest {
  string filename = 1;
}

message FormatResponse {
  string contents = 1;
}

message FsEntry {
  string filename = 2;
  bool isDir = 3;
  repeated FsEntry subFiles = 4;
  // flag for lazy loading
  bool isFetched = 5;
  string isComposeFolder = 6;
  // set when the entry's name is pinned in dockman.yml (pinnedFiles)
  bool pinned = 7;
}

message RenameFile {
  string oldFilePath = 1;
  string newFilePath = 2;
}

message File {
  string filename = 1;
  bool isDir = 2;
}

message Empty {}
